export enum Genre {
    Crime = 0,
    Adventure,
    Documentary,
    Fantasy,
    ScienceFiction,
    Mystery,
    Romance,
    Western,
    Horror,
    Drama,
    Comedy,
    Action,
    War,
    Music,
    TvMovie,
    History,
    Thriller,
    Animation,
    Family,
    Foreign,
}

export const GenreDescriptions: Record<number, string> = {
    [Genre.Crime]: "Crime",
    [Genre.Action]: "Action",
    [Genre.Adventure]: "Adventure",
    [Genre.Animation]: "Animation",
    [Genre.Comedy]: "Comedy",
    [Genre.Documentary]: "Documentary",
    [Genre.Drama]: "Drama",
    [Genre.Family]: "Family",
    [Genre.Fantasy]: "Fantasy",
    [Genre.Foreign]: "Foreign",
    [Genre.History]: "History",
    [Genre.Horror]: "Horror",
    [Genre.Music]: "Music",
    [Genre.Mystery]: "Mystery",
    [Genre.Romance]: "Romance",
    [Genre.ScienceFiction]: "Science Fiction",
    [Genre.Thriller]: "Thriller",
    [Genre.TvMovie]: "Tv Movie",
    [Genre.War]: "War",
    [Genre.Western]: "Western",
};
